development: &default
  adapter: postgresql
  database: <%= ENV.fetch("PG_DATABASE", "reddit_clone_development") %>
#  encoding: utf8
#  host: <%#= ENV.fetch("PG_HOST", "postgres") %>
#  port: <%#= ENV.fetch("PG_PORT", "5432") %>
#  min_messages: warning
#  pool: <%#= Integer(ENV.fetch("PG_POOL", ENV.fetch("RAILS_MAX_THREADS", 5))) %>
#  reaping_frequency: <%#= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
#  timeout: 5000
#  username: <%#= ENV.fetch("PG_USERNAME", "postgres") %>
#  password: <%#= ENV.fetch("PG_PASSWORD", "postgres") %>
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "postgres"

test:
  <<: *default
  database: "reddit_clone_test<%= ENV.fetch('TEST_ENV_NUMBER', '') %>"

production: &deploy
  adapter: postgresql
  database: <%= ENV.fetch("PG_DATABASE", "reddit_clone_production") %>
  encoding: utf8
  host: <%= ENV.fetch("PG_HOST", "postgres") %>
  min_messages: warning
  pool: <%= Integer(ENV.fetch("PG_POOL", ENV.fetch("RAILS_MAX_THREADS", 5))) %>
  timeout: 5000
  username: <%= ENV.fetch("PG_USERNAME", "postgres") %>
  password: <%= ENV.fetch("PG_PASSWORD", "") %>
  sslmode: <%= ENV.fetch("PG_SSLMODE", "disable") %>
